name: Manual Test
on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./
      - run: python --version
      - run: node --version
      - run: dvc --version
      - run: cml --version
